#!/bin/bash

echo "Starting VPN..."
sudo systemctl start wg-quick@wg0

echo "Starting Wi-Fi Hotspot..."
echo "Setting static IP for wlan0..."
sudo ip addr flush dev wlan0
sudo ip addr add 192.168.50.1/24 dev wlan0
sudo ip link set wlan0 up

sudo systemctl start hostapd
sudo systemctl start dnsmasq

echo "Enabling IP forwarding..."
sudo sysctl -w net.ipv4.ip_forward=1

echo "Setting up NAT..."
sudo iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE
sudo iptables -A FORWARD -i wg0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -i wlan0 -o wg0 -j ACCEPT

echo "Hotspot is now active!"

